### PR TITLE
added support for indexing and returning geohashes

### PR DESCRIPTION
**Pull request by dmfenton**
@chelm take a look plz

### CODE REVIEW

**Comment by dmfenton** [comment]
Next commit will be standardizing, package bump and change log but the code is ready to review

**Comment by chelm** [comment]
i dig it

**Comment by dmfenton** [comment]
I'm giving up on Standard for now, it's causing too many headaches. This is ready to go.

**Comment by chelm** [comment]
@dmfenton FYI im working on getting travis.ci set up for this repo

**Comment by chelm** [comment]
this is absurd, all is good locally

**Comment by dmfenton** [comment]
could be a bug in test ENV or something?

**Comment by chelm** [comment]
all good now.

**Pull request merged**
